stages:
  - build
  - deploy

build-image:
  stage: build
  image: fedora:44
  tags:
    - fedora-shell

  before_script:
    - sudo rm -rf out

  script:
    - sudo mkdir build
    - sudo mv ts build/.
    - sudo mv setup-chroot build/.
    - sudo mv README.md build/.
    - cd build
    - sudo ./setup-chroot -i
    - sudo ./setup-chroot -e dnf install -y --setopt=keepcache=1 --setopt=max_parallel_downloads=10 docker
    - sudo ./setup-chroot -e ts/bin/export-docker-images build/packages/nginx-proxy-manager/build/images.conf build/boot-images/grub/efi-source/Docker
    - sudo ./setup-chroot -e cp -a /build/conf/boot2docker/* /build/.
    - sudo ./setup-chroot -e stb
    - sudo mv ts/build/boot-images/grub/thinstation-efi.iso ../npm.iso
    - sudo chown gitlab-runner:gitlab-runner ../npm.iso

  artifacts:
    name: "npm-$CI_COMMIT_SHORT_SHA"
    paths:
      - npm.iso
    expire_in: 14 days

  after_script:
    - sudo rm -rf build

deploy_repo:
  stage: deploy
  script:
    - rsync -av -e "ssh -i /home/gitlab-runner/.ssh/repo_deploy" out/ gitlab-deploy@192.168.22.22:/srv/repo-incoming/